// Code generated by ent, DO NOT EDIT.

package checkinrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the checkinrecord type in the database.
	Label = "checkin_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCheckinDate holds the string denoting the checkin_date field in the database.
	FieldCheckinDate = "checkin_date"
	// FieldDailyReward holds the string denoting the daily_reward field in the database.
	FieldDailyReward = "daily_reward"
	// FieldExtraReward holds the string denoting the extra_reward field in the database.
	FieldExtraReward = "extra_reward"
	// FieldMonthCount holds the string denoting the month_count field in the database.
	FieldMonthCount = "month_count"
	// FieldExtraMilestones holds the string denoting the extra_milestones field in the database.
	FieldExtraMilestones = "extra_milestones"
	// FieldCheckedInAt holds the string denoting the checked_in_at field in the database.
	FieldCheckedInAt = "checked_in_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the checkinrecord in the database.
	Table = "checkin_records"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "checkin_records"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for checkinrecord fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldCheckinDate,
	FieldDailyReward,
	FieldExtraReward,
	FieldMonthCount,
	FieldExtraMilestones,
	FieldCheckedInAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDailyReward holds the default value on creation for the "daily_reward" field.
	DefaultDailyReward float64
	// DefaultExtraReward holds the default value on creation for the "extra_reward" field.
	DefaultExtraReward float64
	// DefaultMonthCount holds the default value on creation for the "month_count" field.
	DefaultMonthCount int
	// DefaultCheckedInAt holds the default value on creation for the "checked_in_at" field.
	DefaultCheckedInAt func() time.Time
)

// OrderOption defines the ordering options for the CheckinRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCheckinDate orders the results by the checkin_date field.
func ByCheckinDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckinDate, opts...).ToFunc()
}

// ByDailyReward orders the results by the daily_reward field.
func ByDailyReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyReward, opts...).ToFunc()
}

// ByExtraReward orders the results by the extra_reward field.
func ByExtraReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtraReward, opts...).ToFunc()
}

// ByMonthCount orders the results by the month_count field.
func ByMonthCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthCount, opts...).ToFunc()
}

// ByCheckedInAt orders the results by the checked_in_at field.
func ByCheckedInAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckedInAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
