// Code generated by ent, DO NOT EDIT.

package checkinrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldUserID, v))
}

// CheckinDate applies equality check predicate on the "checkin_date" field. It's identical to CheckinDateEQ.
func CheckinDate(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldCheckinDate, v))
}

// DailyReward applies equality check predicate on the "daily_reward" field. It's identical to DailyRewardEQ.
func DailyReward(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldDailyReward, v))
}

// ExtraReward applies equality check predicate on the "extra_reward" field. It's identical to ExtraRewardEQ.
func ExtraReward(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldExtraReward, v))
}

// MonthCount applies equality check predicate on the "month_count" field. It's identical to MonthCountEQ.
func MonthCount(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldMonthCount, v))
}

// ConsecutiveCount applies equality check predicate on the "consecutive_count" field. It's identical to ConsecutiveCountEQ.
func ConsecutiveCount(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldConsecutiveCount, v))
}

// CheckedInAt applies equality check predicate on the "checked_in_at" field. It's identical to CheckedInAtEQ.
func CheckedInAt(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldCheckedInAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// CheckinDateEQ applies the EQ predicate on the "checkin_date" field.
func CheckinDateEQ(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldCheckinDate, v))
}

// CheckinDateNEQ applies the NEQ predicate on the "checkin_date" field.
func CheckinDateNEQ(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldCheckinDate, v))
}

// CheckinDateIn applies the In predicate on the "checkin_date" field.
func CheckinDateIn(vs ...time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldCheckinDate, vs...))
}

// CheckinDateNotIn applies the NotIn predicate on the "checkin_date" field.
func CheckinDateNotIn(vs ...time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldCheckinDate, vs...))
}

// CheckinDateGT applies the GT predicate on the "checkin_date" field.
func CheckinDateGT(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldCheckinDate, v))
}

// CheckinDateGTE applies the GTE predicate on the "checkin_date" field.
func CheckinDateGTE(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldCheckinDate, v))
}

// CheckinDateLT applies the LT predicate on the "checkin_date" field.
func CheckinDateLT(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldCheckinDate, v))
}

// CheckinDateLTE applies the LTE predicate on the "checkin_date" field.
func CheckinDateLTE(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldCheckinDate, v))
}

// DailyRewardEQ applies the EQ predicate on the "daily_reward" field.
func DailyRewardEQ(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldDailyReward, v))
}

// DailyRewardNEQ applies the NEQ predicate on the "daily_reward" field.
func DailyRewardNEQ(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldDailyReward, v))
}

// DailyRewardIn applies the In predicate on the "daily_reward" field.
func DailyRewardIn(vs ...float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldDailyReward, vs...))
}

// DailyRewardNotIn applies the NotIn predicate on the "daily_reward" field.
func DailyRewardNotIn(vs ...float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldDailyReward, vs...))
}

// DailyRewardGT applies the GT predicate on the "daily_reward" field.
func DailyRewardGT(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldDailyReward, v))
}

// DailyRewardGTE applies the GTE predicate on the "daily_reward" field.
func DailyRewardGTE(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldDailyReward, v))
}

// DailyRewardLT applies the LT predicate on the "daily_reward" field.
func DailyRewardLT(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldDailyReward, v))
}

// DailyRewardLTE applies the LTE predicate on the "daily_reward" field.
func DailyRewardLTE(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldDailyReward, v))
}

// ExtraRewardEQ applies the EQ predicate on the "extra_reward" field.
func ExtraRewardEQ(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldExtraReward, v))
}

// ExtraRewardNEQ applies the NEQ predicate on the "extra_reward" field.
func ExtraRewardNEQ(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldExtraReward, v))
}

// ExtraRewardIn applies the In predicate on the "extra_reward" field.
func ExtraRewardIn(vs ...float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldExtraReward, vs...))
}

// ExtraRewardNotIn applies the NotIn predicate on the "extra_reward" field.
func ExtraRewardNotIn(vs ...float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldExtraReward, vs...))
}

// ExtraRewardGT applies the GT predicate on the "extra_reward" field.
func ExtraRewardGT(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldExtraReward, v))
}

// ExtraRewardGTE applies the GTE predicate on the "extra_reward" field.
func ExtraRewardGTE(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldExtraReward, v))
}

// ExtraRewardLT applies the LT predicate on the "extra_reward" field.
func ExtraRewardLT(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldExtraReward, v))
}

// ExtraRewardLTE applies the LTE predicate on the "extra_reward" field.
func ExtraRewardLTE(v float64) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldExtraReward, v))
}

// MonthCountEQ applies the EQ predicate on the "month_count" field.
func MonthCountEQ(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldMonthCount, v))
}

// MonthCountNEQ applies the NEQ predicate on the "month_count" field.
func MonthCountNEQ(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldMonthCount, v))
}

// MonthCountIn applies the In predicate on the "month_count" field.
func MonthCountIn(vs ...int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldMonthCount, vs...))
}

// MonthCountNotIn applies the NotIn predicate on the "month_count" field.
func MonthCountNotIn(vs ...int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldMonthCount, vs...))
}

// MonthCountGT applies the GT predicate on the "month_count" field.
func MonthCountGT(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldMonthCount, v))
}

// MonthCountGTE applies the GTE predicate on the "month_count" field.
func MonthCountGTE(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldMonthCount, v))
}

// MonthCountLT applies the LT predicate on the "month_count" field.
func MonthCountLT(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldMonthCount, v))
}

// MonthCountLTE applies the LTE predicate on the "month_count" field.
func MonthCountLTE(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldMonthCount, v))
}

// ConsecutiveCountEQ applies the EQ predicate on the "consecutive_count" field.
func ConsecutiveCountEQ(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldConsecutiveCount, v))
}

// ConsecutiveCountNEQ applies the NEQ predicate on the "consecutive_count" field.
func ConsecutiveCountNEQ(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldConsecutiveCount, v))
}

// ConsecutiveCountIn applies the In predicate on the "consecutive_count" field.
func ConsecutiveCountIn(vs ...int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldConsecutiveCount, vs...))
}

// ConsecutiveCountNotIn applies the NotIn predicate on the "consecutive_count" field.
func ConsecutiveCountNotIn(vs ...int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldConsecutiveCount, vs...))
}

// ConsecutiveCountGT applies the GT predicate on the "consecutive_count" field.
func ConsecutiveCountGT(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldConsecutiveCount, v))
}

// ConsecutiveCountGTE applies the GTE predicate on the "consecutive_count" field.
func ConsecutiveCountGTE(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldConsecutiveCount, v))
}

// ConsecutiveCountLT applies the LT predicate on the "consecutive_count" field.
func ConsecutiveCountLT(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldConsecutiveCount, v))
}

// ConsecutiveCountLTE applies the LTE predicate on the "consecutive_count" field.
func ConsecutiveCountLTE(v int) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldConsecutiveCount, v))
}

// ExtraMilestonesIsNil applies the IsNil predicate on the "extra_milestones" field.
func ExtraMilestonesIsNil() predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIsNull(FieldExtraMilestones))
}

// ExtraMilestonesNotNil applies the NotNil predicate on the "extra_milestones" field.
func ExtraMilestonesNotNil() predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotNull(FieldExtraMilestones))
}

// CheckedInAtEQ applies the EQ predicate on the "checked_in_at" field.
func CheckedInAtEQ(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldEQ(FieldCheckedInAt, v))
}

// CheckedInAtNEQ applies the NEQ predicate on the "checked_in_at" field.
func CheckedInAtNEQ(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNEQ(FieldCheckedInAt, v))
}

// CheckedInAtIn applies the In predicate on the "checked_in_at" field.
func CheckedInAtIn(vs ...time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldIn(FieldCheckedInAt, vs...))
}

// CheckedInAtNotIn applies the NotIn predicate on the "checked_in_at" field.
func CheckedInAtNotIn(vs ...time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldNotIn(FieldCheckedInAt, vs...))
}

// CheckedInAtGT applies the GT predicate on the "checked_in_at" field.
func CheckedInAtGT(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGT(FieldCheckedInAt, v))
}

// CheckedInAtGTE applies the GTE predicate on the "checked_in_at" field.
func CheckedInAtGTE(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldGTE(FieldCheckedInAt, v))
}

// CheckedInAtLT applies the LT predicate on the "checked_in_at" field.
func CheckedInAtLT(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLT(FieldCheckedInAt, v))
}

// CheckedInAtLTE applies the LTE predicate on the "checked_in_at" field.
func CheckedInAtLTE(v time.Time) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.FieldLTE(FieldCheckedInAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CheckinRecord {
	return predicate.CheckinRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CheckinRecord {
	return predicate.CheckinRecord(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CheckinRecord) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CheckinRecord) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CheckinRecord) predicate.CheckinRecord {
	return predicate.CheckinRecord(sql.NotPredicates(p))
}
