// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CheckinRecordCreate is the builder for creating a CheckinRecord entity.
type CheckinRecordCreate struct {
	config
	mutation *CheckinRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CheckinRecordCreate) SetCreatedAt(v time.Time) *CheckinRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CheckinRecordCreate) SetNillableCreatedAt(v *time.Time) *CheckinRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CheckinRecordCreate) SetUpdatedAt(v time.Time) *CheckinRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CheckinRecordCreate) SetNillableUpdatedAt(v *time.Time) *CheckinRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CheckinRecordCreate) SetUserID(v int64) *CheckinRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCheckinDate sets the "checkin_date" field.
func (_c *CheckinRecordCreate) SetCheckinDate(v time.Time) *CheckinRecordCreate {
	_c.mutation.SetCheckinDate(v)
	return _c
}

// SetDailyReward sets the "daily_reward" field.
func (_c *CheckinRecordCreate) SetDailyReward(v float64) *CheckinRecordCreate {
	_c.mutation.SetDailyReward(v)
	return _c
}

// SetNillableDailyReward sets the "daily_reward" field if the given value is not nil.
func (_c *CheckinRecordCreate) SetNillableDailyReward(v *float64) *CheckinRecordCreate {
	if v != nil {
		_c.SetDailyReward(*v)
	}
	return _c
}

// SetExtraReward sets the "extra_reward" field.
func (_c *CheckinRecordCreate) SetExtraReward(v float64) *CheckinRecordCreate {
	_c.mutation.SetExtraReward(v)
	return _c
}

// SetNillableExtraReward sets the "extra_reward" field if the given value is not nil.
func (_c *CheckinRecordCreate) SetNillableExtraReward(v *float64) *CheckinRecordCreate {
	if v != nil {
		_c.SetExtraReward(*v)
	}
	return _c
}

// SetMonthCount sets the "month_count" field.
func (_c *CheckinRecordCreate) SetMonthCount(v int) *CheckinRecordCreate {
	_c.mutation.SetMonthCount(v)
	return _c
}

// SetNillableMonthCount sets the "month_count" field if the given value is not nil.
func (_c *CheckinRecordCreate) SetNillableMonthCount(v *int) *CheckinRecordCreate {
	if v != nil {
		_c.SetMonthCount(*v)
	}
	return _c
}

// SetConsecutiveCount sets the "consecutive_count" field.
func (_c *CheckinRecordCreate) SetConsecutiveCount(v int) *CheckinRecordCreate {
	_c.mutation.SetConsecutiveCount(v)
	return _c
}

// SetNillableConsecutiveCount sets the "consecutive_count" field if the given value is not nil.
func (_c *CheckinRecordCreate) SetNillableConsecutiveCount(v *int) *CheckinRecordCreate {
	if v != nil {
		_c.SetConsecutiveCount(*v)
	}
	return _c
}

// SetExtraMilestones sets the "extra_milestones" field.
func (_c *CheckinRecordCreate) SetExtraMilestones(v []int) *CheckinRecordCreate {
	_c.mutation.SetExtraMilestones(v)
	return _c
}

// SetCheckedInAt sets the "checked_in_at" field.
func (_c *CheckinRecordCreate) SetCheckedInAt(v time.Time) *CheckinRecordCreate {
	_c.mutation.SetCheckedInAt(v)
	return _c
}

// SetNillableCheckedInAt sets the "checked_in_at" field if the given value is not nil.
func (_c *CheckinRecordCreate) SetNillableCheckedInAt(v *time.Time) *CheckinRecordCreate {
	if v != nil {
		_c.SetCheckedInAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CheckinRecordCreate) SetUser(v *User) *CheckinRecordCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CheckinRecordMutation object of the builder.
func (_c *CheckinRecordCreate) Mutation() *CheckinRecordMutation {
	return _c.mutation
}

// Save creates the CheckinRecord in the database.
func (_c *CheckinRecordCreate) Save(ctx context.Context) (*CheckinRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CheckinRecordCreate) SaveX(ctx context.Context) *CheckinRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CheckinRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := checkinrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := checkinrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DailyReward(); !ok {
		v := checkinrecord.DefaultDailyReward
		_c.mutation.SetDailyReward(v)
	}
	if _, ok := _c.mutation.ExtraReward(); !ok {
		v := checkinrecord.DefaultExtraReward
		_c.mutation.SetExtraReward(v)
	}
	if _, ok := _c.mutation.MonthCount(); !ok {
		v := checkinrecord.DefaultMonthCount
		_c.mutation.SetMonthCount(v)
	}
	if _, ok := _c.mutation.ConsecutiveCount(); !ok {
		v := checkinrecord.DefaultConsecutiveCount
		_c.mutation.SetConsecutiveCount(v)
	}
	if _, ok := _c.mutation.CheckedInAt(); !ok {
		v := checkinrecord.DefaultCheckedInAt()
		_c.mutation.SetCheckedInAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CheckinRecordCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CheckinRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CheckinRecord.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CheckinRecord.user_id"`)}
	}
	if _, ok := _c.mutation.CheckinDate(); !ok {
		return &ValidationError{Name: "checkin_date", err: errors.New(`ent: missing required field "CheckinRecord.checkin_date"`)}
	}
	if _, ok := _c.mutation.DailyReward(); !ok {
		return &ValidationError{Name: "daily_reward", err: errors.New(`ent: missing required field "CheckinRecord.daily_reward"`)}
	}
	if _, ok := _c.mutation.ExtraReward(); !ok {
		return &ValidationError{Name: "extra_reward", err: errors.New(`ent: missing required field "CheckinRecord.extra_reward"`)}
	}
	if _, ok := _c.mutation.MonthCount(); !ok {
		return &ValidationError{Name: "month_count", err: errors.New(`ent: missing required field "CheckinRecord.month_count"`)}
	}
	if _, ok := _c.mutation.ConsecutiveCount(); !ok {
		return &ValidationError{Name: "consecutive_count", err: errors.New(`ent: missing required field "CheckinRecord.consecutive_count"`)}
	}
	if _, ok := _c.mutation.CheckedInAt(); !ok {
		return &ValidationError{Name: "checked_in_at", err: errors.New(`ent: missing required field "CheckinRecord.checked_in_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CheckinRecord.user"`)}
	}
	return nil
}

func (_c *CheckinRecordCreate) sqlSave(ctx context.Context) (*CheckinRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CheckinRecordCreate) createSpec() (*CheckinRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckinRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checkinrecord.Table, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(checkinrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(checkinrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CheckinDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckinDate, field.TypeTime, value)
		_node.CheckinDate = value
	}
	if value, ok := _c.mutation.DailyReward(); ok {
		_spec.SetField(checkinrecord.FieldDailyReward, field.TypeFloat64, value)
		_node.DailyReward = value
	}
	if value, ok := _c.mutation.ExtraReward(); ok {
		_spec.SetField(checkinrecord.FieldExtraReward, field.TypeFloat64, value)
		_node.ExtraReward = value
	}
	if value, ok := _c.mutation.MonthCount(); ok {
		_spec.SetField(checkinrecord.FieldMonthCount, field.TypeInt, value)
		_node.MonthCount = value
	}
	if value, ok := _c.mutation.ConsecutiveCount(); ok {
		_spec.SetField(checkinrecord.FieldConsecutiveCount, field.TypeInt, value)
		_node.ConsecutiveCount = value
	}
	if value, ok := _c.mutation.ExtraMilestones(); ok {
		_spec.SetField(checkinrecord.FieldExtraMilestones, field.TypeJSON, value)
		_node.ExtraMilestones = value
	}
	if value, ok := _c.mutation.CheckedInAt(); ok {
		_spec.SetField(checkinrecord.FieldCheckedInAt, field.TypeTime, value)
		_node.CheckedInAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinrecord.UserTable,
			Columns: []string{checkinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckinRecord.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckinRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckinRecordCreate) OnConflict(opts ...sql.ConflictOption) *CheckinRecordUpsertOne {
	_c.conflict = opts
	return &CheckinRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckinRecordCreate) OnConflictColumns(columns ...string) *CheckinRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckinRecordUpsertOne{
		create: _c,
	}
}

type (
	// CheckinRecordUpsertOne is the builder for "upsert"-ing
	//  one CheckinRecord node.
	CheckinRecordUpsertOne struct {
		create *CheckinRecordCreate
	}

	// CheckinRecordUpsert is the "OnConflict" setter.
	CheckinRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CheckinRecordUpsert) SetUpdatedAt(v time.Time) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateUpdatedAt() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckinRecordUpsert) SetUserID(v int64) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateUserID() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldUserID)
	return u
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinRecordUpsert) SetCheckinDate(v time.Time) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldCheckinDate, v)
	return u
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateCheckinDate() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldCheckinDate)
	return u
}

// SetDailyReward sets the "daily_reward" field.
func (u *CheckinRecordUpsert) SetDailyReward(v float64) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldDailyReward, v)
	return u
}

// UpdateDailyReward sets the "daily_reward" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateDailyReward() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldDailyReward)
	return u
}

// AddDailyReward adds v to the "daily_reward" field.
func (u *CheckinRecordUpsert) AddDailyReward(v float64) *CheckinRecordUpsert {
	u.Add(checkinrecord.FieldDailyReward, v)
	return u
}

// SetExtraReward sets the "extra_reward" field.
func (u *CheckinRecordUpsert) SetExtraReward(v float64) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldExtraReward, v)
	return u
}

// UpdateExtraReward sets the "extra_reward" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateExtraReward() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldExtraReward)
	return u
}

// AddExtraReward adds v to the "extra_reward" field.
func (u *CheckinRecordUpsert) AddExtraReward(v float64) *CheckinRecordUpsert {
	u.Add(checkinrecord.FieldExtraReward, v)
	return u
}

// SetMonthCount sets the "month_count" field.
func (u *CheckinRecordUpsert) SetMonthCount(v int) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldMonthCount, v)
	return u
}

// UpdateMonthCount sets the "month_count" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateMonthCount() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldMonthCount)
	return u
}

// AddMonthCount adds v to the "month_count" field.
func (u *CheckinRecordUpsert) AddMonthCount(v int) *CheckinRecordUpsert {
	u.Add(checkinrecord.FieldMonthCount, v)
	return u
}

// SetConsecutiveCount sets the "consecutive_count" field.
func (u *CheckinRecordUpsert) SetConsecutiveCount(v int) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldConsecutiveCount, v)
	return u
}

// UpdateConsecutiveCount sets the "consecutive_count" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateConsecutiveCount() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldConsecutiveCount)
	return u
}

// AddConsecutiveCount adds v to the "consecutive_count" field.
func (u *CheckinRecordUpsert) AddConsecutiveCount(v int) *CheckinRecordUpsert {
	u.Add(checkinrecord.FieldConsecutiveCount, v)
	return u
}

// SetExtraMilestones sets the "extra_milestones" field.
func (u *CheckinRecordUpsert) SetExtraMilestones(v []int) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldExtraMilestones, v)
	return u
}

// UpdateExtraMilestones sets the "extra_milestones" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateExtraMilestones() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldExtraMilestones)
	return u
}

// ClearExtraMilestones clears the value of the "extra_milestones" field.
func (u *CheckinRecordUpsert) ClearExtraMilestones() *CheckinRecordUpsert {
	u.SetNull(checkinrecord.FieldExtraMilestones)
	return u
}

// SetCheckedInAt sets the "checked_in_at" field.
func (u *CheckinRecordUpsert) SetCheckedInAt(v time.Time) *CheckinRecordUpsert {
	u.Set(checkinrecord.FieldCheckedInAt, v)
	return u
}

// UpdateCheckedInAt sets the "checked_in_at" field to the value that was provided on create.
func (u *CheckinRecordUpsert) UpdateCheckedInAt() *CheckinRecordUpsert {
	u.SetExcluded(checkinrecord.FieldCheckedInAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckinRecordUpsertOne) UpdateNewValues() *CheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(checkinrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CheckinRecordUpsertOne) Ignore() *CheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckinRecordUpsertOne) DoNothing() *CheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckinRecordCreate.OnConflict
// documentation for more info.
func (u *CheckinRecordUpsertOne) Update(set func(*CheckinRecordUpsert)) *CheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckinRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CheckinRecordUpsertOne) SetUpdatedAt(v time.Time) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateUpdatedAt() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CheckinRecordUpsertOne) SetUserID(v int64) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateUserID() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinRecordUpsertOne) SetCheckinDate(v time.Time) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetCheckinDate(v)
	})
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateCheckinDate() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateCheckinDate()
	})
}

// SetDailyReward sets the "daily_reward" field.
func (u *CheckinRecordUpsertOne) SetDailyReward(v float64) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetDailyReward(v)
	})
}

// AddDailyReward adds v to the "daily_reward" field.
func (u *CheckinRecordUpsertOne) AddDailyReward(v float64) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddDailyReward(v)
	})
}

// UpdateDailyReward sets the "daily_reward" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateDailyReward() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateDailyReward()
	})
}

// SetExtraReward sets the "extra_reward" field.
func (u *CheckinRecordUpsertOne) SetExtraReward(v float64) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetExtraReward(v)
	})
}

// AddExtraReward adds v to the "extra_reward" field.
func (u *CheckinRecordUpsertOne) AddExtraReward(v float64) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddExtraReward(v)
	})
}

// UpdateExtraReward sets the "extra_reward" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateExtraReward() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateExtraReward()
	})
}

// SetMonthCount sets the "month_count" field.
func (u *CheckinRecordUpsertOne) SetMonthCount(v int) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetMonthCount(v)
	})
}

// AddMonthCount adds v to the "month_count" field.
func (u *CheckinRecordUpsertOne) AddMonthCount(v int) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddMonthCount(v)
	})
}

// UpdateMonthCount sets the "month_count" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateMonthCount() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateMonthCount()
	})
}

// SetConsecutiveCount sets the "consecutive_count" field.
func (u *CheckinRecordUpsertOne) SetConsecutiveCount(v int) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetConsecutiveCount(v)
	})
}

// AddConsecutiveCount adds v to the "consecutive_count" field.
func (u *CheckinRecordUpsertOne) AddConsecutiveCount(v int) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddConsecutiveCount(v)
	})
}

// UpdateConsecutiveCount sets the "consecutive_count" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateConsecutiveCount() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateConsecutiveCount()
	})
}

// SetExtraMilestones sets the "extra_milestones" field.
func (u *CheckinRecordUpsertOne) SetExtraMilestones(v []int) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetExtraMilestones(v)
	})
}

// UpdateExtraMilestones sets the "extra_milestones" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateExtraMilestones() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateExtraMilestones()
	})
}

// ClearExtraMilestones clears the value of the "extra_milestones" field.
func (u *CheckinRecordUpsertOne) ClearExtraMilestones() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.ClearExtraMilestones()
	})
}

// SetCheckedInAt sets the "checked_in_at" field.
func (u *CheckinRecordUpsertOne) SetCheckedInAt(v time.Time) *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetCheckedInAt(v)
	})
}

// UpdateCheckedInAt sets the "checked_in_at" field to the value that was provided on create.
func (u *CheckinRecordUpsertOne) UpdateCheckedInAt() *CheckinRecordUpsertOne {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateCheckedInAt()
	})
}

// Exec executes the query.
func (u *CheckinRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckinRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckinRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CheckinRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CheckinRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CheckinRecordCreateBulk is the builder for creating many CheckinRecord entities in bulk.
type CheckinRecordCreateBulk struct {
	config
	err      error
	builders []*CheckinRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the CheckinRecord entities in the database.
func (_c *CheckinRecordCreateBulk) Save(ctx context.Context) ([]*CheckinRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CheckinRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckinRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CheckinRecordCreateBulk) SaveX(ctx context.Context) []*CheckinRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckinRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckinRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckinRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *CheckinRecordUpsertBulk {
	_c.conflict = opts
	return &CheckinRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckinRecordCreateBulk) OnConflictColumns(columns ...string) *CheckinRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckinRecordUpsertBulk{
		create: _c,
	}
}

// CheckinRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of CheckinRecord nodes.
type CheckinRecordUpsertBulk struct {
	create *CheckinRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckinRecordUpsertBulk) UpdateNewValues() *CheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(checkinrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckinRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CheckinRecordUpsertBulk) Ignore() *CheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckinRecordUpsertBulk) DoNothing() *CheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckinRecordCreateBulk.OnConflict
// documentation for more info.
func (u *CheckinRecordUpsertBulk) Update(set func(*CheckinRecordUpsert)) *CheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckinRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CheckinRecordUpsertBulk) SetUpdatedAt(v time.Time) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateUpdatedAt() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CheckinRecordUpsertBulk) SetUserID(v int64) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateUserID() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinRecordUpsertBulk) SetCheckinDate(v time.Time) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetCheckinDate(v)
	})
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateCheckinDate() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateCheckinDate()
	})
}

// SetDailyReward sets the "daily_reward" field.
func (u *CheckinRecordUpsertBulk) SetDailyReward(v float64) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetDailyReward(v)
	})
}

// AddDailyReward adds v to the "daily_reward" field.
func (u *CheckinRecordUpsertBulk) AddDailyReward(v float64) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddDailyReward(v)
	})
}

// UpdateDailyReward sets the "daily_reward" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateDailyReward() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateDailyReward()
	})
}

// SetExtraReward sets the "extra_reward" field.
func (u *CheckinRecordUpsertBulk) SetExtraReward(v float64) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetExtraReward(v)
	})
}

// AddExtraReward adds v to the "extra_reward" field.
func (u *CheckinRecordUpsertBulk) AddExtraReward(v float64) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddExtraReward(v)
	})
}

// UpdateExtraReward sets the "extra_reward" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateExtraReward() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateExtraReward()
	})
}

// SetMonthCount sets the "month_count" field.
func (u *CheckinRecordUpsertBulk) SetMonthCount(v int) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetMonthCount(v)
	})
}

// AddMonthCount adds v to the "month_count" field.
func (u *CheckinRecordUpsertBulk) AddMonthCount(v int) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddMonthCount(v)
	})
}

// UpdateMonthCount sets the "month_count" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateMonthCount() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateMonthCount()
	})
}

// SetConsecutiveCount sets the "consecutive_count" field.
func (u *CheckinRecordUpsertBulk) SetConsecutiveCount(v int) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetConsecutiveCount(v)
	})
}

// AddConsecutiveCount adds v to the "consecutive_count" field.
func (u *CheckinRecordUpsertBulk) AddConsecutiveCount(v int) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.AddConsecutiveCount(v)
	})
}

// UpdateConsecutiveCount sets the "consecutive_count" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateConsecutiveCount() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateConsecutiveCount()
	})
}

// SetExtraMilestones sets the "extra_milestones" field.
func (u *CheckinRecordUpsertBulk) SetExtraMilestones(v []int) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetExtraMilestones(v)
	})
}

// UpdateExtraMilestones sets the "extra_milestones" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateExtraMilestones() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateExtraMilestones()
	})
}

// ClearExtraMilestones clears the value of the "extra_milestones" field.
func (u *CheckinRecordUpsertBulk) ClearExtraMilestones() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.ClearExtraMilestones()
	})
}

// SetCheckedInAt sets the "checked_in_at" field.
func (u *CheckinRecordUpsertBulk) SetCheckedInAt(v time.Time) *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.SetCheckedInAt(v)
	})
}

// UpdateCheckedInAt sets the "checked_in_at" field to the value that was provided on create.
func (u *CheckinRecordUpsertBulk) UpdateCheckedInAt() *CheckinRecordUpsertBulk {
	return u.Update(func(s *CheckinRecordUpsert) {
		s.UpdateCheckedInAt()
	})
}

// Exec executes the query.
func (u *CheckinRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CheckinRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckinRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckinRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
