// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CheckinRecordUpdate is the builder for updating CheckinRecord entities.
type CheckinRecordUpdate struct {
	config
	hooks    []Hook
	mutation *CheckinRecordMutation
}

// Where appends a list predicates to the CheckinRecordUpdate builder.
func (_u *CheckinRecordUpdate) Where(ps ...predicate.CheckinRecord) *CheckinRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CheckinRecordUpdate) SetUpdatedAt(v time.Time) *CheckinRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CheckinRecordUpdate) SetUserID(v int64) *CheckinRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckinRecordUpdate) SetNillableUserID(v *int64) *CheckinRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *CheckinRecordUpdate) SetCheckinDate(v time.Time) *CheckinRecordUpdate {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *CheckinRecordUpdate) SetNillableCheckinDate(v *time.Time) *CheckinRecordUpdate {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetDailyReward sets the "daily_reward" field.
func (_u *CheckinRecordUpdate) SetDailyReward(v float64) *CheckinRecordUpdate {
	_u.mutation.ResetDailyReward()
	_u.mutation.SetDailyReward(v)
	return _u
}

// SetNillableDailyReward sets the "daily_reward" field if the given value is not nil.
func (_u *CheckinRecordUpdate) SetNillableDailyReward(v *float64) *CheckinRecordUpdate {
	if v != nil {
		_u.SetDailyReward(*v)
	}
	return _u
}

// AddDailyReward adds value to the "daily_reward" field.
func (_u *CheckinRecordUpdate) AddDailyReward(v float64) *CheckinRecordUpdate {
	_u.mutation.AddDailyReward(v)
	return _u
}

// SetExtraReward sets the "extra_reward" field.
func (_u *CheckinRecordUpdate) SetExtraReward(v float64) *CheckinRecordUpdate {
	_u.mutation.ResetExtraReward()
	_u.mutation.SetExtraReward(v)
	return _u
}

// SetNillableExtraReward sets the "extra_reward" field if the given value is not nil.
func (_u *CheckinRecordUpdate) SetNillableExtraReward(v *float64) *CheckinRecordUpdate {
	if v != nil {
		_u.SetExtraReward(*v)
	}
	return _u
}

// AddExtraReward adds value to the "extra_reward" field.
func (_u *CheckinRecordUpdate) AddExtraReward(v float64) *CheckinRecordUpdate {
	_u.mutation.AddExtraReward(v)
	return _u
}

// SetMonthCount sets the "month_count" field.
func (_u *CheckinRecordUpdate) SetMonthCount(v int) *CheckinRecordUpdate {
	_u.mutation.ResetMonthCount()
	_u.mutation.SetMonthCount(v)
	return _u
}

// SetNillableMonthCount sets the "month_count" field if the given value is not nil.
func (_u *CheckinRecordUpdate) SetNillableMonthCount(v *int) *CheckinRecordUpdate {
	if v != nil {
		_u.SetMonthCount(*v)
	}
	return _u
}

// AddMonthCount adds value to the "month_count" field.
func (_u *CheckinRecordUpdate) AddMonthCount(v int) *CheckinRecordUpdate {
	_u.mutation.AddMonthCount(v)
	return _u
}

// SetExtraMilestones sets the "extra_milestones" field.
func (_u *CheckinRecordUpdate) SetExtraMilestones(v []int) *CheckinRecordUpdate {
	_u.mutation.SetExtraMilestones(v)
	return _u
}

// AppendExtraMilestones appends value to the "extra_milestones" field.
func (_u *CheckinRecordUpdate) AppendExtraMilestones(v []int) *CheckinRecordUpdate {
	_u.mutation.AppendExtraMilestones(v)
	return _u
}

// ClearExtraMilestones clears the value of the "extra_milestones" field.
func (_u *CheckinRecordUpdate) ClearExtraMilestones() *CheckinRecordUpdate {
	_u.mutation.ClearExtraMilestones()
	return _u
}

// SetCheckedInAt sets the "checked_in_at" field.
func (_u *CheckinRecordUpdate) SetCheckedInAt(v time.Time) *CheckinRecordUpdate {
	_u.mutation.SetCheckedInAt(v)
	return _u
}

// SetNillableCheckedInAt sets the "checked_in_at" field if the given value is not nil.
func (_u *CheckinRecordUpdate) SetNillableCheckedInAt(v *time.Time) *CheckinRecordUpdate {
	if v != nil {
		_u.SetCheckedInAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CheckinRecordUpdate) SetUser(v *User) *CheckinRecordUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CheckinRecordMutation object of the builder.
func (_u *CheckinRecordUpdate) Mutation() *CheckinRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CheckinRecordUpdate) ClearUser() *CheckinRecordUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckinRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckinRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CheckinRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := checkinrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckinRecordUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckinRecord.user"`)
	}
	return nil
}

func (_u *CheckinRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinrecord.Table, checkinrecord.Columns, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(checkinrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckinDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DailyReward(); ok {
		_spec.SetField(checkinrecord.FieldDailyReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyReward(); ok {
		_spec.AddField(checkinrecord.FieldDailyReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExtraReward(); ok {
		_spec.SetField(checkinrecord.FieldExtraReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExtraReward(); ok {
		_spec.AddField(checkinrecord.FieldExtraReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthCount(); ok {
		_spec.SetField(checkinrecord.FieldMonthCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonthCount(); ok {
		_spec.AddField(checkinrecord.FieldMonthCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExtraMilestones(); ok {
		_spec.SetField(checkinrecord.FieldExtraMilestones, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExtraMilestones(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, checkinrecord.FieldExtraMilestones, value)
		})
	}
	if _u.mutation.ExtraMilestonesCleared() {
		_spec.ClearField(checkinrecord.FieldExtraMilestones, field.TypeJSON)
	}
	if value, ok := _u.mutation.CheckedInAt(); ok {
		_spec.SetField(checkinrecord.FieldCheckedInAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinrecord.UserTable,
			Columns: []string{checkinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinrecord.UserTable,
			Columns: []string{checkinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckinRecordUpdateOne is the builder for updating a single CheckinRecord entity.
type CheckinRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckinRecordMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CheckinRecordUpdateOne) SetUpdatedAt(v time.Time) *CheckinRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CheckinRecordUpdateOne) SetUserID(v int64) *CheckinRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckinRecordUpdateOne) SetNillableUserID(v *int64) *CheckinRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *CheckinRecordUpdateOne) SetCheckinDate(v time.Time) *CheckinRecordUpdateOne {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *CheckinRecordUpdateOne) SetNillableCheckinDate(v *time.Time) *CheckinRecordUpdateOne {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetDailyReward sets the "daily_reward" field.
func (_u *CheckinRecordUpdateOne) SetDailyReward(v float64) *CheckinRecordUpdateOne {
	_u.mutation.ResetDailyReward()
	_u.mutation.SetDailyReward(v)
	return _u
}

// SetNillableDailyReward sets the "daily_reward" field if the given value is not nil.
func (_u *CheckinRecordUpdateOne) SetNillableDailyReward(v *float64) *CheckinRecordUpdateOne {
	if v != nil {
		_u.SetDailyReward(*v)
	}
	return _u
}

// AddDailyReward adds value to the "daily_reward" field.
func (_u *CheckinRecordUpdateOne) AddDailyReward(v float64) *CheckinRecordUpdateOne {
	_u.mutation.AddDailyReward(v)
	return _u
}

// SetExtraReward sets the "extra_reward" field.
func (_u *CheckinRecordUpdateOne) SetExtraReward(v float64) *CheckinRecordUpdateOne {
	_u.mutation.ResetExtraReward()
	_u.mutation.SetExtraReward(v)
	return _u
}

// SetNillableExtraReward sets the "extra_reward" field if the given value is not nil.
func (_u *CheckinRecordUpdateOne) SetNillableExtraReward(v *float64) *CheckinRecordUpdateOne {
	if v != nil {
		_u.SetExtraReward(*v)
	}
	return _u
}

// AddExtraReward adds value to the "extra_reward" field.
func (_u *CheckinRecordUpdateOne) AddExtraReward(v float64) *CheckinRecordUpdateOne {
	_u.mutation.AddExtraReward(v)
	return _u
}

// SetMonthCount sets the "month_count" field.
func (_u *CheckinRecordUpdateOne) SetMonthCount(v int) *CheckinRecordUpdateOne {
	_u.mutation.ResetMonthCount()
	_u.mutation.SetMonthCount(v)
	return _u
}

// SetNillableMonthCount sets the "month_count" field if the given value is not nil.
func (_u *CheckinRecordUpdateOne) SetNillableMonthCount(v *int) *CheckinRecordUpdateOne {
	if v != nil {
		_u.SetMonthCount(*v)
	}
	return _u
}

// AddMonthCount adds value to the "month_count" field.
func (_u *CheckinRecordUpdateOne) AddMonthCount(v int) *CheckinRecordUpdateOne {
	_u.mutation.AddMonthCount(v)
	return _u
}

// SetExtraMilestones sets the "extra_milestones" field.
func (_u *CheckinRecordUpdateOne) SetExtraMilestones(v []int) *CheckinRecordUpdateOne {
	_u.mutation.SetExtraMilestones(v)
	return _u
}

// AppendExtraMilestones appends value to the "extra_milestones" field.
func (_u *CheckinRecordUpdateOne) AppendExtraMilestones(v []int) *CheckinRecordUpdateOne {
	_u.mutation.AppendExtraMilestones(v)
	return _u
}

// ClearExtraMilestones clears the value of the "extra_milestones" field.
func (_u *CheckinRecordUpdateOne) ClearExtraMilestones() *CheckinRecordUpdateOne {
	_u.mutation.ClearExtraMilestones()
	return _u
}

// SetCheckedInAt sets the "checked_in_at" field.
func (_u *CheckinRecordUpdateOne) SetCheckedInAt(v time.Time) *CheckinRecordUpdateOne {
	_u.mutation.SetCheckedInAt(v)
	return _u
}

// SetNillableCheckedInAt sets the "checked_in_at" field if the given value is not nil.
func (_u *CheckinRecordUpdateOne) SetNillableCheckedInAt(v *time.Time) *CheckinRecordUpdateOne {
	if v != nil {
		_u.SetCheckedInAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CheckinRecordUpdateOne) SetUser(v *User) *CheckinRecordUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CheckinRecordMutation object of the builder.
func (_u *CheckinRecordUpdateOne) Mutation() *CheckinRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CheckinRecordUpdateOne) ClearUser() *CheckinRecordUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CheckinRecordUpdate builder.
func (_u *CheckinRecordUpdateOne) Where(ps ...predicate.CheckinRecord) *CheckinRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckinRecordUpdateOne) Select(field string, fields ...string) *CheckinRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CheckinRecord entity.
func (_u *CheckinRecordUpdateOne) Save(ctx context.Context) (*CheckinRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinRecordUpdateOne) SaveX(ctx context.Context) *CheckinRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckinRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CheckinRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := checkinrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckinRecordUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckinRecord.user"`)
	}
	return nil
}

func (_u *CheckinRecordUpdateOne) sqlSave(ctx context.Context) (_node *CheckinRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinrecord.Table, checkinrecord.Columns, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckinRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkinrecord.FieldID)
		for _, f := range fields {
			if !checkinrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkinrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(checkinrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckinDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DailyReward(); ok {
		_spec.SetField(checkinrecord.FieldDailyReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyReward(); ok {
		_spec.AddField(checkinrecord.FieldDailyReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExtraReward(); ok {
		_spec.SetField(checkinrecord.FieldExtraReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExtraReward(); ok {
		_spec.AddField(checkinrecord.FieldExtraReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthCount(); ok {
		_spec.SetField(checkinrecord.FieldMonthCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonthCount(); ok {
		_spec.AddField(checkinrecord.FieldMonthCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExtraMilestones(); ok {
		_spec.SetField(checkinrecord.FieldExtraMilestones, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExtraMilestones(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, checkinrecord.FieldExtraMilestones, value)
		})
	}
	if _u.mutation.ExtraMilestonesCleared() {
		_spec.ClearField(checkinrecord.FieldExtraMilestones, field.TypeJSON)
	}
	if value, ok := _u.mutation.CheckedInAt(); ok {
		_spec.SetField(checkinrecord.FieldCheckedInAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinrecord.UserTable,
			Columns: []string{checkinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinrecord.UserTable,
			Columns: []string{checkinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CheckinRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
