// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CheckinRecord is the model entity for the CheckinRecord schema.
type CheckinRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CheckinDate holds the value of the "checkin_date" field.
	CheckinDate time.Time `json:"checkin_date,omitempty"`
	// DailyReward holds the value of the "daily_reward" field.
	DailyReward float64 `json:"daily_reward,omitempty"`
	// ExtraReward holds the value of the "extra_reward" field.
	ExtraReward float64 `json:"extra_reward,omitempty"`
	// MonthCount holds the value of the "month_count" field.
	MonthCount int `json:"month_count,omitempty"`
	// ConsecutiveCount holds the value of the "consecutive_count" field.
	ConsecutiveCount int `json:"consecutive_count,omitempty"`
	// ExtraMilestones holds the value of the "extra_milestones" field.
	ExtraMilestones []int `json:"extra_milestones,omitempty"`
	// CheckedInAt holds the value of the "checked_in_at" field.
	CheckedInAt time.Time `json:"checked_in_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CheckinRecordQuery when eager-loading is set.
	Edges        CheckinRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CheckinRecordEdges holds the relations/edges for other nodes in the graph.
type CheckinRecordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheckinRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheckinRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checkinrecord.FieldExtraMilestones:
			values[i] = new([]byte)
		case checkinrecord.FieldDailyReward, checkinrecord.FieldExtraReward:
			values[i] = new(sql.NullFloat64)
		case checkinrecord.FieldID, checkinrecord.FieldUserID, checkinrecord.FieldMonthCount, checkinrecord.FieldConsecutiveCount:
			values[i] = new(sql.NullInt64)
		case checkinrecord.FieldCreatedAt, checkinrecord.FieldUpdatedAt, checkinrecord.FieldCheckinDate, checkinrecord.FieldCheckedInAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheckinRecord fields.
func (_m *CheckinRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checkinrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case checkinrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case checkinrecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case checkinrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case checkinrecord.FieldCheckinDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_date", values[i])
			} else if value.Valid {
				_m.CheckinDate = value.Time
			}
		case checkinrecord.FieldDailyReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_reward", values[i])
			} else if value.Valid {
				_m.DailyReward = value.Float64
			}
		case checkinrecord.FieldExtraReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field extra_reward", values[i])
			} else if value.Valid {
				_m.ExtraReward = value.Float64
			}
		case checkinrecord.FieldMonthCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field month_count", values[i])
			} else if value.Valid {
				_m.MonthCount = int(value.Int64)
			}
		case checkinrecord.FieldConsecutiveCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_count", values[i])
			} else if value.Valid {
				_m.ConsecutiveCount = int(value.Int64)
			}
		case checkinrecord.FieldExtraMilestones:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra_milestones", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtraMilestones); err != nil {
					return fmt.Errorf("unmarshal field extra_milestones: %w", err)
				}
			}
		case checkinrecord.FieldCheckedInAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_in_at", values[i])
			} else if value.Valid {
				_m.CheckedInAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheckinRecord.
// This includes values selected through modifiers, order, etc.
func (_m *CheckinRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CheckinRecord entity.
func (_m *CheckinRecord) QueryUser() *UserQuery {
	return NewCheckinRecordClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this CheckinRecord.
// Note that you need to call CheckinRecord.Unwrap() before calling this method if this CheckinRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CheckinRecord) Update() *CheckinRecordUpdateOne {
	return NewCheckinRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CheckinRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CheckinRecord) Unwrap() *CheckinRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheckinRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CheckinRecord) String() string {
	var builder strings.Builder
	builder.WriteString("CheckinRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("checkin_date=")
	builder.WriteString(_m.CheckinDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("daily_reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyReward))
	builder.WriteString(", ")
	builder.WriteString("extra_reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtraReward))
	builder.WriteString(", ")
	builder.WriteString("month_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthCount))
	builder.WriteString(", ")
	builder.WriteString("consecutive_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveCount))
	builder.WriteString(", ")
	builder.WriteString("extra_milestones=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtraMilestones))
	builder.WriteString(", ")
	builder.WriteString("checked_in_at=")
	builder.WriteString(_m.CheckedInAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CheckinRecords is a parsable slice of CheckinRecord.
type CheckinRecords []*CheckinRecord
