ARG GOLANG_IMAGE=golang:1.26.6-alpine

FROM ${GOLANG_IMAGE}

ARG AIR_VERSION=v1.67.4
ARG GOPROXY=https://goproxy.cn,direct
ARG GOSUMDB="sum.golang.org https://goproxy.cn/sumdb/sum.golang.org"

ENV GOPROXY=${GOPROXY} \
    GOSUMDB=${GOSUMDB}

RUN apk add --no-cache ca-certificates git tzdata && \
    go install github.com/air-verse/air@${AIR_VERSION}

WORKDIR /app

CMD ["air", "-c", ".air.toml"]
